version: '3.0'

expectations:
  population_size: 1000

actions:


# actions to plot deaths over time

  generate_cohort_deaths:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_deaths --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_deaths.csv


  plot_deaths:
    run: r:latest analysis/1-plot-deaths.R
    needs: [generate_cohort_deaths]
    outputs:
      moderately_sensitive:
        log: output/logs/log-1-plot-deaths.txt
        figure1: output/plots/plot_deaths.png
        figure2: output/plots/plot_cmldeaths_age.png

# actions to plot gp activity over time

  generate_cohort_activity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_activity --index-date-range "2020-01-01 to 2020-09-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_activity_*.csv

  generate_measures_activity:
    run: cohortextractor:latest generate_measures --study-definition study_definition_activity --output-dir=output/measures
    needs: [generate_cohort_activity]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv 

  plot_measures:
    run: r:latest analysis/1-plot-measures.R
    needs: [generate_measures_activity]
    outputs:
      moderately_sensitive:
        log: output/logs/log-1-plot-measures.txt
        figure: output/plots/plot_*.png
       

  run_all:
    needs: [plot_measures, plot_deaths]
    # In order to be valid this action needs to define a run commmand and
    # some output. We don't really care what these are but the below seems to
    # do the trick.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
